### ISSUE TITLE
Unsubscribe keyboard shortcuts if window is hidden/closed

### ISSUE THREAD

**Issue by akashnimare** [zulip/zulip-electron#106]
Here - https://github.com/zulip/zulip-electron/blob/master/app/main/index.js#L184

**Comment by jajodiaraghav** [comment]
@akashnimare Is that different from https://github.com/zulip/zulip-electron/blob/master/app/main/index.js#L181?
How can we approach this one?

**Comment by akashnimare** [comment]
@jajodiaraghav I forgot to close this. It's already fixed 😄
