### ISSUE TITLE
Set User-Agent and message sending client as ZulipElectron/version

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-electron#108]
We need to change two things:

(1) We should set the User-Agent string for HTTP requests made from the electron app to be e.g. ZulipElectron/0.7.2, so that server-side code can identify the app

(2) This block in static/js/compose.js in the webapp needs to have code for detecting if we're in the electron app and reporting itself as ZulipElectron.

```
function client() {                                                                                  
    if ((window.bridge !== undefined) &&                                                             
        (window.bridge.desktopAppVersion !== undefined)) {                                           
        return "desktop app " + window.bridge.desktopAppVersion();                                   
    }                                                                                                
    return "website";                                                                                
}                                                                                                    
```

**Comment by akashnimare** [comment]
> (1) We should set the User-Agent string for HTTP requests made from the electron app to be e.g. ZulipElectron/0.7.2, so that server-side code can identify the app


@timabbott I have added 'ZulipElectron/0.5.8' as a user-agent. Can you cross-test it? BTW here is the default user-agent - 
`"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Zulip/0.5.7 Chrome/53.0.2785.143 Electron/1.4.7 Safari/537.36"`

**Comment by timabbott** [comment]
Looking at 34bb55cb9f805921d40f4ca4c30dd5282affc9cc, we should try to make sure it gets updated in every release; one strategy is to have a version.js file that everything else can read, and then have a "build a release" script that writes to that file in addition to doing the git tag, etc., to make sure we always do it.

I think it's fine to include the other details (it'll at least indicate Mac vs. Linux) later on in the string.

**Comment by timabbott** [comment]
I confirmed the User-Agent is appearing properly on the server; as I noted you may still

I'll take care of part 2; just figured out what we need to do.

**Comment by timabbott** [comment]
OK, the Zulip server should now do the right thing.  We'll be able to tell if we succeeded based on whether chat.zulip.org/stats starts showing ZulipElectron usage.

I'm going to leave this open for doign the "append at front" approach for adjusting the user-agent string rather than just truncating it to ZulipElectron.

**Comment by akashnimare** [comment]
Fixed here https://github.com/zulip/zulip-electron/commit/34bb55cb9f805921d40f4ca4c30dd5282affc9cc. Now it will be like ZulipElectron + Current app version + OS details (linux/darwin/win32). Useragent for current verison on Mac - `ZulipElectron/0.5.8_darwin`. @timabbott anything to add/remove ?

**Comment by timabbott** [comment]
Usually one spells OS details after a space, e.g. `ZulipElectron/0.5.8 darwin`  Could be worth providing additional details on OS like what version though -- e.g. Windows 7 and Windows 10 are pretty different...

**Comment by akashnimare** [comment]
Current status -
 
**Windows 7** - 
`ZulipElectron/0.5.8 Windows 7
`

**Windows 10** -
`ZulipElectron/0.5.8 Windows 10`


**Mac** -
`ZulipElectron/0.5.8 Mac
`

**Linux** -
`ZulipElectron/0.5.8 Linux`

**Comment by timabbott** [comment]
Cool.  Would consider adding OS X version (and Linux version details) as well when we get a chance, but those are less urgent so could be put in a follow-up issue.  

Thanks @akashnimare!

**Comment by timabbott** [comment]
Closing as duplicate of #172.
