### ISSUE TITLE
Internal zulip links should be opened in-app

### ISSUE THREAD

**Issue by jjst** [zulip/zulip-electron#11]
I think there is one exception to #9 where we want to open links in-app rather than in an external browser window: for zulip internal links, e.g. when linking to another stream.

For example, clicking on https://zulip.com/#narrow/stream/test-bot/subject/rsvpbot from the electron app will open a new tab in my browser, but I think it should update the current view of the zulip electron app instead.

**Comment by timabbott** [comment]
yeah, I agree that's probably how this should work.

**Comment by akashnimare** [comment]
@jjst @timabbott Fixed it. Can you guys confirm it? You will have to **npm install** before running app.

**Comment by jjst** [comment]
Just tested it, I can confirm it now opens the links in-app.

**Comment by jjst** [comment]
I think this regressed. I'm using fa4172281d824253ad2e2391a7dc1ef69910e0ed and internal links open in-browser while external links open in-app.

**Comment by akashnimare** [comment]
@jjst are you still having this issue? all Internal zulip links should be open in app and external one should be open in browser.

**Comment by akashnimare** [comment]
@jjst got it. It's not working as expected. I don't know what went wrong from [33fb06c](https://github.com/zulip/zulip-electron/tree/33fb06c5c5eb76ec91268e09d810da2c9ef8b460)  to [fa41722](https://github.com/zulip/zulip-electron/commit/fa4172281d824253ad2e2391a7dc1ef69910e0ed). Could you debug this?

**Comment by akashnimare** [comment]
@jjst now it's working properly :smiley_cat:.

**Comment by akashnimare** [comment]
Internal links works fine but now external links are also opening in app.

**Comment by alkuzad** [comment]
links to sites opens in app instead of browser/new tab so I can not follow them

**Comment by akashnimare** [comment]
@alkuzad external links are still opening in app. I am working on this.

**Comment by akashnimare** [comment]
@jjst @alkuzad hopefully it should work now. Can you guys test it?

**Comment by jjst** [comment]
Can confirm it behaves as it should now. Also I'm loving your use of emojis in :octocat: commit messages! :grinning:

**Comment by akashnimare** [comment]
@jjst finally :stuck_out_tongue:, emojis are great way to show your current state of mind :neckbeard: .

**Comment by alkuzad** [comment]
@akashnimare works, thanks for this
