### ISSUE TITLE
Desktop notifications stopped working

### ISSUE THREAD

**Issue by akashnimare** [zulip/zulip-electron#111]
---
Please include: 
> Operating System

All

**Comment by akashnimare** [comment]
It's because of the new user-agent we have added in #108

**Comment by akashnimare** [comment]
I think it's nesseccary to add the default user-agent i.e.- `"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Zulip/0.5.8 Chrome/53.0.2785.143 Electron/1.4.7 Safari/537.36"` in our new user agent which is - `ZulipElectron/0.5.8 Mac` to make desktop notifications work properly.

**Comment by timabbott** [comment]
OK.  Why don't we try `ZulipElectron/0.5.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Zulip/0.5.8 Chrome/53.0.2785.143 Electron/1.4.7 Safari/537.36` as the User-Agent?  (i.e. just appending the Zulip thing at the beginning)?

**Comment by akashnimare** [comment]
@timabbott ahaa, I have already tried it and it works pretty well. So the new user agent would be - 
`ZulipElectron/0.5.8 Mac Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Zulip/0.5.8 Chrome/53.0.2785.143 Electron/1.4.7 Safari/537.36`

**Comment by timabbott** [comment]
That sounds great.

**Comment by akashnimare** [comment]
Fixed in https://github.com/zulip/zulip-electron/commit/bfc03c7e959384da982376b881f336d2e40449ac.
