### ISSUE TITLE
No error message when internet is not working

### ISSUE THREAD

**Issue by singh1114** [zulip/zulip-electron#114]
---
Please include: 
- `Operating System:` Ubuntu 16.04

- `Clear steps to reproduce the issue:`
When we get disconnected to the internet and click on login button it opens up a blank page without showing any error and when we are again connected to the internet, we have to click on reload for the app to show something again. 

- `Relevant error messages and/or screenshots`

**Comment by singh1114** [comment]
Even when the app starts it shows a blank screen. A good user experience would be to add a message that tells the user that the messages are being fetched from the server.

**Comment by akashnimare** [comment]
It's a known issue. Probably we should first check the internet connection through window.navigator.onLine or something and then proceed further.

**Comment by jajodiaraghav** [comment]
Claiming

**Comment by akashnimare** [comment]
@jajodiaraghav do you want to work on this?

**Comment by jajodiaraghav** [comment]
Yes. Will submit a PR soon!

**Comment by akashnimare** [comment]
Awesome. Let me know if you need any help.

**Comment by singh1114** [comment]
This might be helpful.
@akashnimare, @jajodiaraghav 
https://www.npmjs.com/package/is-online

**Comment by timabbott** [comment]
@jajodiaraghav you can use `@zulipbot  claim` to claim an issue.
