### ISSUE TITLE
Allow disabling swipe gesture on OSX

### ISSUE THREAD

**Issue by IsaacChapman** [zulip/zulip-electron#132]
I view a lot of code snippets and/or other "wide" content in Zulip, and find its default behavior on OS X of window navigation when I use a two-finger swipe to scroll through content in the current window annoying. Enough so that I created the attached script to remove https://github.com/zulip/zulip-electron/blob/master/app/main/preload.js#L13-L14 from my local app when/if my local Zulip app is updated.
[zulip-disable-swipe.sh.txt](https://github.com/zulip/zulip-electron/files/868948/zulip-disable-swipe.sh.txt)

**Comment by timabbott** [comment]
@akashnimare do you think we should make this a setting, or just remove that code for everyone?

**Comment by akashnimare** [comment]
This is an experimental feature for macOS; if nobody seems to use it we could just remove it for now.

**Comment by akashnimare** [comment]
Okay, removing this experimental feature for now. Will make it optional once we have the centralized preference settings .
