### ISSUE TITLE
Build failing on OS X 10.12.4

### ISSUE THREAD

**Issue by syncopated** [zulip/zulip-electron#133]
---
I'm able to run the app successfully via `npm start` but running `npm run dist` to build a .dmg fails.

OS: OS X 10.12.4
node.js version: 6.10.1
npm version: 3.10.10

Steps to reproduce:

1. clone repo
2. run `npm install`
3. run `npm run dist`

npm-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dist' ]
2 info using npm@3.10.10
3 info using node@v6.10.1
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info lifecycle zulip@0.5.8~predist: zulip@0.5.8
6 silly lifecycle zulip@0.5.8~predist: no script for predist, continuing
7 info lifecycle zulip@0.5.8~dist: zulip@0.5.8
8 verbose lifecycle zulip@0.5.8~dist: unsafe-perm in lifecycle true
9 verbose lifecycle zulip@0.5.8~dist: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/davidson/dev/projects/zulip-electron/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle zulip@0.5.8~dist: CWD: /Users/davidson/dev/projects/zulip-electron
11 silly lifecycle zulip@0.5.8~dist: Args: [ '-c', 'build' ]
12 silly lifecycle zulip@0.5.8~dist: Returned: code: 255  signal: null
13 info lifecycle zulip@0.5.8~dist: Failed to exec dist script
14 verbose stack Error: zulip@0.5.8 dist: `build`
14 verbose stack Exit status 255
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid zulip@0.5.8
16 verbose cwd /Users/davidson/dev/projects/zulip-electron
17 error Darwin 16.5.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dist"
19 error node v6.10.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error zulip@0.5.8 dist: `build`
22 error Exit status 255
23 error Failed at the zulip@0.5.8 dist script 'build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the zulip package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs zulip
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls zulip
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by akashnimare** [comment]
@syncopated thanks for opening this issue :)
I have pushed a fix, could you please try again on master?

**Comment by syncopated** [comment]
@akashnimare your fix worked. I ran `npm run dist` and it built the .dmg successfully. Thanks!

**Comment by akashnimare** [comment]
Yayyyy 🎉
