### ISSUE TITLE
Right-click on stream/topic name to copy its URL

### ISSUE THREAD

**Issue by jjst** [zulip/zulip-electron#15]
On the web version of zulip, when using it in a browser it's possible to right-click on a stream or topic name and then use the browser's context menu to copy its URL and share it. As far as I know there is no equivalent way to perform this action in the electron app, as there is no context menu displayed when right-clicking on stream/topics.

**Comment by akashnimare** [comment]
Thanks for opening this issue. There is no default context menu option in electron. This feature is in my to-do list.

**Comment by akashnimare** [comment]
We could use this https://github.com/sindresorhus/electron-context-menu

**Comment by akashnimare** [comment]
@jjst It's fixed. I have added a very basic version of context menu.
