### ISSUE TITLE
Add desktop notifications support on Windows 7

### ISSUE THREAD

**Issue by alkuzad** [zulip/zulip-electron#16]
According to electron documentation Notification api does not work on Windows7, it has to use Tray baloon api. 

Is it possible to implement baloon notifications ? It would most propably require work also on standard website.

**Comment by akashnimare** [comment]
@alkuzad As of now only native notifications works in our app. I think we could implement balloon notifications for Windows7.

**Comment by akashnimare** [comment]
@alkuzad we could use [node-notifier](https://www.npmjs.com/package/node-notifier).

**Comment by alkuzad** [comment]
@akashnimare but as current code relies on the web code it is not doable right ? The web code should then use wrapper over Notification create to send event so electron can catch it.

**Comment by akashnimare** [comment]
If native notifications works on win7 then we could easily wrap it around electron.

**Comment by mgrabow1** [comment]
Windows 8.1 - also no desktop notifications for new messages. Only audible.

**Comment by akashnimare** [comment]
Here are the few things we need to work on - 
* Make the native notifications clickable on linux + windows
* Add windows 7 + 8 support

**Comment by mgrabow1** [comment]
I'm waiting and waiting... ;)
I've just made a major upgrade do 1.5.1 and sadly some features (like administration, settings and stream settings) don't work in native Windows client (also message textarea became very small). 
I regularly check the electron version, but lack of desktop notofication (on W7 and W8 - most computer in our organization) is really a major drawback :/

**Comment by timabbott** [comment]
Yeah that seems pretty poor; @akashnimare how hard would it be to make this work on W7/W8?

**Comment by akashnimare** [comment]
@timabbott it's hard since Electron does not support desktop notifications on windows 7. I guess we have to wait until they fix this issue. @mgrabow1 @alkuzad you can also track it here -
https://github.com/electron/electron/issues/262
https://github.com/electron/electron/issues/8384

> I regularly check the electron version, but lack of desktop notifications (on W7 and W8 - most computers in our organization) is really a major drawback :/

@mgrabow1 sorry for not working on this feature. Our primary focus is to make a stable windows app first with some basic features (spellchecker, auto-updates, signed app etc) and then implement desktop notifications(w7/w8), multiple login server etc. Now that we have a stable release [v0.5.8,](https://github.com/zulip/zulip-electron/releases/tag/v0.5.8) we could look into this feature.

I don't think electron will fix this issue in near future so we gotta implement this on our own. [node-notifier](https://github.com/mikaelbr/node-notifier) and [electron-toaster](https://github.com/s-a/electron-toaster) are two possible alternatives which we could use.

**Comment by timabbott** [comment]
Yeah, I agree that it's unlikely Electron will fix this soon.  As a stopgap if those libraries are hard to setup, we could at least make sure the browser-style web notifications work on those platforms.

**Comment by mgrabow1** [comment]
Thanks for your replies. Some people in my organization (including myself) started using web-based client (for now), but some sceptics are hard to convince that our great IM-replacement doesn't notfiy about new messages ;)
A follow up question - is this notification thing also connected to not changing zulip-electron tray icon after receiving messages? The native client's icon "blinks" with the number of unread messages. Will zulip-electron do that after resolving this issue? (IMHO it would be enough for some time - to me it's more important to know that anone wrote anything than to get rich notifications :)

**Comment by alkuzad** [comment]
@akashnimare made comment here: https://github.com/electron/electron/issues/262#issuecomment-280297669

**Comment by akashnimare** [comment]
@alkuzad cool. I think [electron-toaster](https://github.com/s-a/electron-toaster) + [electron-notification-shim](https://github.com/seriema/electron-notification-shim) could resolve this issue.
Last time I checked electron-notification-shim, it used to create double notifications. I'll have to figure out how to delete the native notifications first and then implement notifications using this module 😅 

> We switched to Rocket.Chat

Just curious, any particular reason for switching?

**Comment by alkuzad** [comment]
@akashnimare I personally like zulip more as it has a lot cleaner interface, more compact which is better for bigger companies. But RC is easy to setup with ready docker containers where Zulip warns everywhere that stepping outside Vagrant (which is dead cause real working VM managers costs lots of money and docker works on every modern linux for free) will be painful. 

Stepping outside Ubuntu is painful too (i.e Centos instructions doesn't mention installing redis first, when Ubuntu ones does).

So this is why we have one blessed config that goes around teams that "just works", no one managed to install Zulip without it. 

Also being able to just ctrl+c, ctrl+v screenshot is a big deal, with zulip I had to go via disk always.
@akashnimare I personally like zulip more as it has a lot cleaner interface, more compact which is better for bigger companies. But RC is easy to setup with ready docker containers where Zulip warns everywhere that stepping outside Vagrant (which is dead cause real working VM managers costs lots of money and docker works on every modern linux for free) will be painful. 

Stepping outside Ubuntu is painful too (i.e Centos instructions doesn't mention installing redis first, when Ubuntu ones does).

So this is why we have one blessed config that goes around teams that "just works", no one managed to install Zulip without it. 

Also being able to just ctrl+c, ctrl+v screenshot is a big deal, with zulip I had to go via disk always.

**Comment by akashnimare** [comment]
@alkuzad thanks, we'll take a note on this. cc @timabbott @showell

**Comment by akashnimare** [comment]
> is this notification thing also connected to not changing zulip-electron tray icon after receiving messages?

@mgrabow1 could you please open a new issue for this? Unread counts support is added in OSX only.


![image](https://cloud.githubusercontent.com/assets/2263909/23063107/d4af23a6-f52e-11e6-851a-aad514f9c307.png)


As of now, Electron does not support it but I think there might be other ways to achieve the same.

**Comment by mgrabow1** [comment]
@akashnimare sure, no problem.

Reported as #110

**Comment by akashnimare** [comment]
Windows 7 notification will be implemented once this PR gets merged 

https://github.com/electron/brightray/pull/279 🙇

**Comment by akashnimare** [comment]
![windows 7](https://user-images.githubusercontent.com/2263909/27002110-6130475e-4df6-11e7-8165-8f5ec8edadc0.png)


Windows 7 desktop notification support has been added and will be pushed in next release. Thanks, @alkuzad, @mgrabow1.
