### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by mohdalam** [zulip/zulip-electron#18]
while installing zulip on Ubuntu 16.04 i get error below is the npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart Zulip-desktop@0.0.1
6 info start Zulip-desktop@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info Zulip-desktop@0.0.1 Failed to exec start script
9 verbose stack Error: Zulip-desktop@0.0.1 start: `electron .`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid Zulip-desktop@0.0.1
11 verbose cwd /home/maqbool/Play/zulip-electron
12 error Linux 4.4.0-31-generic
13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
14 error node v4.4.7
15 error npm  v2.15.8
16 error code ELIFECYCLE
17 error Zulip-desktop@0.0.1 start: `electron .`
17 error Exit status 1
18 error Failed at the Zulip-desktop@0.0.1 start script 'electron .'.
18 error This is most likely a problem with the Zulip-desktop package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     electron .
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs Zulip-desktop
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls Zulip-desktop
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by mohdalam** [comment]
solved

**Comment by mohdalam** [comment]
problem fixed

**Comment by akashnimare** [comment]
@mohdalam btw what was the issue? You need to use a greater version of `npm^3.3.5` and `node^4`.
