### ISSUE TITLE
Menu icon

### ISSUE THREAD

**Issue by GervaisdeM** [zulip/zulip-electron#24]
I'm running macOS Sierra, so take this feedback with a grain of salt.

Minor critique: the Z icon in the macOS menu bar is a too big and looks out of place.

**Comment by GervaisdeM** [comment]
![screen shot 2016-07-27 at 4 53 44 pm](https://cloud.githubusercontent.com/assets/963514/17190062/c97f9822-541a-11e6-9112-5a889c53c269.png)

**Comment by timabbott** [comment]
Nice, yeah, we should definitely shrink that :)

**Comment by akashnimare** [comment]
App is using png image for icon. On mac it should use .icns. Need to change it [here](https://github.com/zulip/zulip-electron/blob/master/app/main/tray.js#L20).

**Comment by akashnimare** [comment]
@GervaisdeM I have added a new tray icon which is little smaller than the last one. Let me know if it looks good.

**Comment by GervaisdeM** [comment]
Looks great!
![screen shot 2016-08-04 at 9 16 52 am](https://cloud.githubusercontent.com/assets/963514/17401483/4e9cf590-5a24-11e6-8df2-601f85ab01ce.png)
