### ISSUE TITLE
Window size and position between launches

### ISSUE THREAD

**Issue by GervaisdeM** [zulip/zulip-electron#28]
Electron always opens centered on screen and with what must be a default window size.

I like to make my window smaller with "Display user list on left side in narrow windows." and push it into the upper right of my screen. It does not save my settings between launches.

**Comment by akashnimare** [comment]
@GervaisdeM We are not saving the last window settings/state anywhere. I think we should save it somewhere. I'm working on this.

**Comment by akashnimare** [comment]
@GervaisdeM I have added this feature. Let me know if it's working properly. It might not work as expected on OSX.

**Comment by GervaisdeM** [comment]
@akashnimare 
👍 
Works great!

**Comment by akashnimare** [comment]
Yayy :tada:

**Comment by akashnimare** [comment]
@GervaisdeM just wanted to cross-check if you faced this issue recently?
