### ISSUE TITLE
Check Spelling While Typing.

### ISSUE THREAD

**Issue by GervaisdeM** [zulip/zulip-electron#30]
*Check Spelling While Typing* doesn't underline misspelled words in Zulip Client.
This also never worked in the legacy client, but I thought it worth mentioning.

macOS Sierra

See no red squiggly lines:
![screen shot 2016-07-27 at 5 50 51 pm](https://cloud.githubusercontent.com/assets/963514/17191940/ce21f336-5422-11e6-8dec-763e3f5d22cd.png)

**Comment by akashnimare** [comment]
@GervaisdeM this feature is definitely in our roadmap.

**Comment by akashnimare** [comment]
Added very basic version of spell checker. Currently it doesn't show any suggestions for misspelled word.  
![image](https://cloud.githubusercontent.com/assets/2263909/17279781/44ba8a14-579b-11e6-8268-ad22729e05ce.png)

**Comment by akashnimare** [comment]
@GervaisdeM Can you test it out?

**Comment by GervaisdeM** [comment]
Hi @akashnimare 

I'm sorry... I should have commented earlier. I launch my copy of the client with a small script that looks like this:

```
#!/bin/bash

cd ~/Development/GdeM/zulip-electron/
git pull
npm upgrade
npm start &
```

I've been using the version with spell checking since you added it and it works great. As you mentioned above, it shows all the spelling errors without being able to make suggestions. Love what you have done so far. 👍

**Comment by akashnimare** [comment]
@GervaisdeM Thanks 🚀
