### ISSUE TITLE
Toggle - Verbage

### ISSUE THREAD

**Issue by GervaisdeM** [zulip/zulip-electron#31]
It's unclear what "Toggle" does in the Zulip menu. IMO, this should be reworded as "Toggle Window"

macOS

**Comment by akashnimare** [comment]
@timabbott Do we really need this button (Toggel)? @GervaisdeM is it useful?

**Comment by GervaisdeM** [comment]
I won't use it. I can't speak for all users. I suppose some folks might want to be able to open and close the Zulip window without logging out or hiding the window in some other way.

This may be present in the Electron version because it can be done in the older legacy desktop client.

**Comment by timabbott** [comment]
I think with a better name like "Show/Hide Window" (with the appropriate one visible depending on the state), this is probably a feature some folks will use, but I don't think it's a high-value feature.

**Comment by akashnimare** [comment]
I rarely use it. Let me remove it then.
