### ISSUE TITLE
Close Zulip window JavaScript error

### ISSUE THREAD

**Issue by GervaisdeM** [zulip/zulip-electron#32]
macOS Sierra

If I close the main Zulip window, there is no way to reopen it.

If I select "Toggle," I get the following error:
<img width="401" alt="screen shot 2016-07-27 at 8 50 09 pm" src="https://cloud.githubusercontent.com/assets/963514/17196537/db3d9b60-543b-11e6-8859-ac2f73e24e85.png">

If I select "Change Zulip Server," the blue window with the add button opens. If I enter the URL to my server, I receive the following error:
<img width="403" alt="screen shot 2016-07-27 at 8 53 30 pm" src="https://cloud.githubusercontent.com/assets/963514/17196653/90b54d94-543c-11e6-86d9-7e54dd6b1f14.png">

**Comment by GervaisdeM** [comment]
I installed the git, nodejs on Windows 10 to test. App looks a bit better on Windows. The above error can't occur because the application closes when the window is closed.

**Comment by akashnimare** [comment]
@GervaisdeM thanks for opening this. There are some electron apis which doesn't work seamlessly on every platform. Applications gets close on window and linux when you click close button but on mac it shows different behaviour.

**Comment by akashnimare** [comment]
@GervaisdeM are you still having this issue? Could you tell me the steps to reproduce it?

**Comment by GervaisdeM** [comment]
@akashnimare Yes. This problem still exists. My original issue was the "Toggle" option in the Zulip menu... Now that this has been removed, the issue still exists and can be triggered with the reload menu item.

On macOS you can trigger it by:

1. Closing the main with the standard "red dot" in the upper left.
<img width="390" alt="screen shot 2016-08-09 at 6 30 51 am" src="https://cloud.githubusercontent.com/assets/963514/17511762/e15d8104-5dfa-11e6-89f0-25ef15f6bbca.png">
2. Select "Reload" form the Zulip menu.
<img width="185" alt="screen shot 2016-08-09 at 6 32 19 am" src="https://cloud.githubusercontent.com/assets/963514/17511808/1139dd8c-5dfb-11e6-950e-741ae8017e53.png">

Error:
<img width="420" alt="screen shot 2016-08-09 at 6 33 03 am" src="https://cloud.githubusercontent.com/assets/963514/17511825/27c26ab0-5dfb-11e6-88e4-ff28618a41dd.png">

**Comment by akashnimare** [comment]
@GervaisdeM fixed. Could you test it now?

**Comment by GervaisdeM** [comment]
@akashnimare 

1. Close the main window
2. Select "reload" from the menu
3. Nothing happens at all.
4. Select "Change Zulip Server"
5. Type in server address and click "Add"
6. 💣

![screen shot 2016-08-09 at 9 37 32 am](https://cloud.githubusercontent.com/assets/963514/17516532/3b029bc6-5e15-11e6-9a1e-c931a3edac2c.png)

**Comment by akashnimare** [comment]
I have pushed a temporary fixed for now. You won't get those errors now. Following actions are not available when the window is closed on OSX - 

> Reload
> Change Zulip server
> log-out
> Keyboard shortcuts

I don't think it's good idea to show these menus when the main window is destroyed. @GervaisdeM what do you think? Although this could change in future.

**Comment by GervaisdeM** [comment]
@akashnimare 
I think anything is better than a crash, but IMO it's odd to leave an application running that has a bunch of menu items that seem to simply not work. Can the application simply close out (like it does on Windows)? If not and this is the only easy way forward, then 👍 

I can however still make it crash...

1. Close main window
2. Try menu options... The only one that works is "About"
3. With the About window open, it seems that Reload still works (It looks like the about window reloads)
4. The "Change Zulip server" also has regained its ability to cause an error.

![screen shot 2016-08-09 at 11 13 26 am](https://cloud.githubusercontent.com/assets/963514/17519599/05b58a2e-5e23-11e6-8613-a2800224e634.png)

There are some errors that scroll by in my terminal window that I have included in the screenshot just in case they are of any interest. The client still works when they complain, so I assume they are innocuous and will just be ignored for now (forever).

**Comment by akashnimare** [comment]
> With the About window open, it seems that Reload still works (It looks like the about window reloads)

> The "Change Zulip server" also has regained its ability to cause an error.

Awesome debugging 😃 .  The problem is I'm not able to get the main window once it's destroyed/closed.

**Comment by akashnimare** [comment]
@GervaisdeM Please test it now.

**Comment by GervaisdeM** [comment]
@akashnimare works great now. I can select "Change Zulip server" from the "Z" menu and it opens the correct window, makes the connection to the server and reloads... very nice.
😄 👍

**Comment by akashnimare** [comment]
@GervaisdeM It works as expected now. Reopen if you face any issue with this 🐎 .
