### ISSUE TITLE
Help menu options should include Zulip link & version

### ISSUE THREAD

**Issue by brainwane** [zulip/zulip-electron#33]
The options in the Help menu currently all go to general Electron help pages on the web. I suggest we add an item that links specifically to https://github.com/zulip/zulip-electron and potentially also an item linking to http://zulip.org/ . It would also be great if it were easily possible for the user to get at the Zulip-electron app version number from somewhere in the Help menu.

**Comment by akashnimare** [comment]
We are using the default menu items provided by electron. Needs to be changed.

**Comment by akashnimare** [comment]
@brainwane updated. Test it please.

**Comment by brainwane** [comment]
@akashnimare I would prefer for the text to more clearly indicate that this is the version number of the desktop app, not of the underlying Zulip core.

**Comment by akashnimare** [comment]
@brainwane so what could we use here? ex

> Zulip Desktop - v0.0.1

**Comment by brainwane** [comment]
@akashnimare I bet @timabbott has branding decisions to make for the long run, about how we brand/name the desktop app. But for right now, I like your suggestion.

**Comment by timabbott** [comment]
Maybe call it "Zulip Electron Desktop" for now, and we'll drop the "Electron" once we've made this the default desktop app.
