### ISSUE TITLE
/apps (and similar documentation pages) should probably load in browser, not in-app

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-electron#34]
Or if we do load them in-app, we should at least provide a back button sort of thing to get back :)

(I tried alt-leftarrow, but it doesn't do anything).

**Comment by GervaisdeM** [comment]
The "Zulip" icon/name in the upper left reloads the standard window. It's not super intuitive if you have not already clicked it 100 times to return "Home," but it does work. Adding a tool tip to that link might be part of the solution.

**Comment by akashnimare** [comment]
I think it's good idea to load app related stuffs in app only. We could change it. As of now there is no way to get back in app. Maybe I need to add a back button or a keyboard shortcut for this.

**Comment by akashnimare** [comment]
@timabbott I am adding a keyboard shortcut to go back. What should be preferable command for this?

> Win / Linux - Backspace
> Osx - Delete

or something else?

**Comment by akashnimare** [comment]
@timabbott I think `Alt+leftarrow` is a right choice. For some reason it's not working so as of now I have added `cmdorctrl+leftarrow` to go back. I'll change it later.

**Comment by timabbott** [comment]
Yeah, alt+leftarrow is what I'm used to.

**Comment by akashnimare** [comment]
Added 👍 .
