### ISSUE TITLE
Document how to switch realms

### ISSUE THREAD

**Issue by brainwane** [zulip/zulip-electron#35]
After I initially install the app and tell it what realm I want it to connect to, I don't see any explanation within the app (or the README) telling me how I would switch realms if I wanted to. Is the current answer that I should manually edit `domain.json`? If so, let's put that in the README, at least until we add a UI for it (the File menu would be a good place to do that).

**Comment by brainwane** [comment]
(Manually editing `domain.json` does seem to work.)

**Comment by akashnimare** [comment]
You can use tray menu `Change Zulip server` for this. 

![image](https://cloud.githubusercontent.com/assets/2263909/17231087/7cc3b346-553d-11e6-90f0-858e4a65d2e4.png)

**Comment by timabbott** [comment]
It might make sense to also put that option in the window's menus, as well, to maximize discoverability (speaking of which, I think those are currently all default links to Electron docs)

**Comment by akashnimare** [comment]
Yeah, we could do that.

**Comment by brainwane** [comment]
I'd love it if this were also in a menu in the window! I did not think at all of checking the icon in the system tray.

**Comment by akashnimare** [comment]
@timabbott menu updated. Is there anything else I should include in window's menu?

**Comment by timabbott** [comment]
@akashnimare There's something wrong with some of the menus where there are blank spaces:

![image](https://cloud.githubusercontent.com/assets/2746074/17499239/034e5222-5d81-11e6-8791-b2f0adf6c062.png)

I might also put the "About" page in the "File" menu (which I'd rename to "Zulip desktop"); I think "View" is a fine menu name (and "Edit" we should get rid of unless we have things to put it in).

**Comment by akashnimare** [comment]
Menu looks fine on ubuntu 14.04.

![menu_228060938056499333](https://cloud.githubusercontent.com/assets/2263909/17572765/f128a5e4-5f73-11e6-810f-b67ecaff60d6.gif)

**Comment by timabbott** [comment]
Cool, I'm on Ubuntu 16.04

**Comment by brainwane** [comment]
@akashnimare the dialog box that pops up when I select "Change Zulip server" from the File menu does successfully let me switch realms -- yay! But it doesn't have a border so it looks less polished than the desktop app's main window, the CSS doesn't match the  and the icon for it in the taskbar does not have an icon.
 
![zulip-borderless-window-screenshot](https://cloud.githubusercontent.com/assets/842790/17605054/8b50c06c-5fe6-11e6-81e7-722149403263.png)

And just now I tried right-clicking on the Z icon in the tray and choosing "Change Zulip server", and there was no response/effect. I'm on Mint 17.

**Comment by akashnimare** [comment]
@brainwane thanks for reporting this. I'm into other things for few days. I'll get back to this issue later 🏃 .

**Comment by timabbott** [comment]
I guess we should look into the Linux Mint tray icon issue here at some point?

**Comment by akashnimare** [comment]
> And just now I tried right-clicking on the Z icon in the tray and choosing "Change Zulip server", and there was no response/effect. I'm on Mint 17.

@brainwane can you reproduce this now?

**Comment by timabbott** [comment]
For context, in master we've completely rewritten the relevant UI.
