### ISSUE TITLE
Problems with entering Zulip server name

### ISSUE THREAD

**Issue by kchen** [zulip/zulip-electron#36]
I just launched zulip-electron, and am attempting to enter the name of my Zulip server.  After entering it, I get "Not valid url", and if I click the OK button there, the window goes blank.  The error message appears to be because of #25, but the window should not go blank.  Since the app asks for a server name and not a url, the error message should probably also mention the server name instead of "url".

In addition, while entering the server name, pressing backspace doesn't have any effect.

**Comment by akashnimare** [comment]
@kchen thanks for opening this. I am not handling the callback function properly i.e when user enters a invalid url. I am working on a new homepage that will completely solve this issue.

**Comment by rwbarton** [comment]
The backspace thing is #37; try the delete key instead for now.

**Comment by brockwhittaker** [comment]
I also encountered this bug.

**Comment by akashnimare** [comment]
@brockwhittaker @kchen fixed. Can you guys test it?

**Comment by kchen** [comment]
Looks good to me. Thanks!  (I previously entered a valid Zulip server, so I only tested this with the "Change zulip server" functionality, since I don't know how to wipe that state.)

It'd be useful if the Esc button closed the box, but the X close button is an obvious alternative to that.

**Comment by akashnimare** [comment]
@kchen Esc support added 🚀 .
