### ISSUE TITLE
Backspace key doesn't work

### ISSUE THREAD

**Issue by hlieberman** [zulip/zulip-electron#37]
In the "Enter a Server URL Box", the backspace key doesn't work.  Delete, however, does.

This is probably some stupid X11 related nonsense.

**Comment by akashnimare** [comment]
@hlieberman I think it got mixed up with [this](https://github.com/zulip/zulip-electron/blob/master/app/main/index.js#L136). Backspace key is not working since it's registered for going back functionality. I'll have to change it.

**Comment by akashnimare** [comment]
@hlieberman fixed.
