### ISSUE TITLE
Integrate chrome extensions

### ISSUE THREAD

**Issue by brainwane** [zulip/zulip-electron#39]
Users might like to log into their Zulip realms using passwords from their password managers (which are sometimes cloud-based and sometimes desktop-based). Can we make an Electron app aware of password managers and use them when possible?

**Comment by akashnimare** [comment]
I'm not sure how to add this but brave browser is doing it [here](https://github.com/brave/browser-laptop/blob/e19913e44050826b6113736015979b33ac138529/app/extensions/brave/content/scripts/passwordManager.js) so I think it's possible to implement.

**Comment by priyank-p** [comment]
@brainwane @akashnimare there is a way to add extensions to chrome app but with some caveats:
  * They do not show up in the app
  * They were meant to be used internally be electron app like for example react-dev-tools for devlopment. 
Although password are saved like local chrome browsers we do not need to implement one altleast i dont think so.

ping @hackerkid i think this should not be in the GCI Tasks

**Comment by hackerkid** [comment]
hmm. @akashnimare handed me this over as task for GCI. He is away for a few days I think. @timabbott thoughts on this?

**Comment by timabbott** [comment]
Yeah, this doesn't really seem in-scope for GCI (seems like a lot of work).  It's also not clear to me that this is a reasonable feature for us to build regardless.  

So I'm going to close this as wontfix; @hackerkid can you remove the GCI task when you get a chance?

Thanks @cPhost for posting about this :)

**Comment by hackerkid** [comment]
Task deleted. Thanks again @cPhost for reporting this. :)
