### ISSUE TITLE
Add support for the desktop app's `window.bridge` API

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-electron#4]
Checking `window.bridge` is how code in the existing Zulip webapp checks for whether it is running inside the desktop app (as opposed to inside the main webapp).  We should review the `window.bridge` related code in the webapp to decide whether all of those cases make sense for the Electron app, and implement an appropriate interface to make use of those hooks.

**Comment by akashnimare** [comment]
I am not sure what `window.bridge` does. Is it related to [spectron](http://electron.atom.io/spectron/). Also see https://github.com/zulip/zulip-electron/issues/6#issuecomment-246083381.

**Comment by timabbott** [comment]
`window.bridge` was used in the Zulip webapp to trigger special behavior for the legacy Zulip desktop app in the webapp's code.  For example, it sets the user-agent equivalent ("client") in compose.js to identify that a user is using the desktop app rather than the webapp, and a bunch of stuff related to native notifications.  You can grep for it in the Zulip main server repository to see:

```
$ git grep window.bridge
static/js/compose.js:    if ((window.bridge !== undefined) &&
static/js/compose.js:        (window.bridge.desktopAppVersion !== undefined)) {
static/js/compose.js:        return "desktop app " + window.bridge.desktopAppVersion();
static/js/compose.js:    if (window.bridge) {
static/js/copy_and_paste.js:    if (window.bridge !== undefined) {
static/js/notifications.js:        // window.bridge is the desktop client
static/js/notifications.js:        (window.bridge !== undefined);
static/js/notifications.js:    if (window.bridge !== undefined) {
static/js/notifications.js:if (window.bridge !== undefined) {
static/js/notifications.js:    window.bridge.updateCount(0);
static/js/notifications.js:    if (window.bridge !== undefined) {
static/js/notifications.js:        window.bridge.updateCount(new_message_count);
static/js/notifications.js:    if (window.bridge !== undefined && window.bridge.updatePMCount !== undefined) {
static/js/notifications.js:        window.bridge.updatePMCount(new_pm_count);
static/js/notifications.js:    if (window.bridge === undefined && notice_memory[key] !== undefined) {
static/js/notifications.js:    if (window.bridge === undefined && notification.webkit_notify === true) {
static/js/notifications.js:        window.bridge.desktopNotification(title, content, notification_source);
static/js/notifications.js:            if (window.bridge !== undefined) {
static/js/notifications.js:                window.bridge.bell();
static/js/notifications.js:    if (typeof(bridge) !== 'undefined' && window.bridge === undefined) {
static/js/notifications.js:        window.bridge = bridge;
static/js/ui.js:    if (window.bridge !== undefined) {
```

We probably don't want to use exactly the same behavior, so maybe we want to add a check for "are we the electron app" in most (but not all!) of those places.  

Does that make sense?  I'm happy to chat about any of those individual if statements and whether they should be applied to the Electron app as well...

**Comment by akashnimare** [comment]
@timabbott I'm trying to find the way to implement this in our electron app 🤔

**Comment by akashnimare** [comment]
Will be fixed in #108

**Comment by akashnimare** [comment]
@timabbott should we consider closing this issue since we have added the user-agent for electron? Also, [this](https://github.com/zulip/zulip/blob/1ba7d1ec68b73204ec79bcae1439e3852b8644bc/zerver/models.py#L1169) should be **ZulipElectron**.

**Comment by timabbott** [comment]
I think I removed the User-agent relevant code from the web frontend a while back.

How is the desktop app currently getting access to unread counts data?

**Comment by zhongyi-tong** [comment]
@timabbott From the title.

**Comment by timabbott** [comment]
@geeeeeeeeek makes sense.  I think probably we can close this issue, but note that if we want to do richer notifications stuff (e.g. to support doing something different if there are unread PMs), something like window.bridge is probably the way to do it.

Finally, that should be "zulipelectron", note this line: https://github.com/zulip/zulip/blob/1ba7d1ec68b73204ec79bcae1439e3852b8644bc/zerver/models.py#L1166

Probably we should change that models.py code to be more readable though (where the thing that appears in the code is not the lower-cased version).
