### ISSUE TITLE
investigate localstorage situation

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-electron#41]
This is a question which could turn into an issue -- does the electron app have local storage enabled?  We use it for handling a few code paths in Zulip (generally around cases like if you have a partially-composed message and then reload), and it'd be good to understand if we should expect that work in the new desktop app.

**Comment by timabbott** [comment]
The main test case is to connect to a development server, ctrl-C the server, and then try to send a message.  The message will fail to send (in particular, no timestamp will show up, which means the message has only been echoed locally and hasn't been received by the server).  Then start the server again, and reload the browser -- the message you tried to send should be automatically transmitted (rather than being lost) and you confirm with a timestamp showing up.

**Comment by vedantrathore** [comment]
@timabbott @akashnimare I would like to work on this, any hints?

**Comment by timabbott** [comment]
@vedantrathore sorry for the slow reply; there's now an easier way to test, which is to see whether the new drafts feature available on chat.zulip.org works.

**Comment by akashnimare** [comment]
✅  Confirming that local storage works in app. 

![image](https://cloud.githubusercontent.com/assets/2263909/24243609/aec3d876-0fe1-11e7-8256-bad5b095e51d.png)
