### ISSUE TITLE
Notifications - count

### ISSUE THREAD

**Issue by GervaisdeM** [zulip/zulip-electron#43]
The notifications often report the wrong number on new messages.

For example, a message comes in and I read it.
Then two more messages come in and Electron/Zulip tells me that there are three messages. I read those.
Then another message comes in and notification reads: 4 messages.

I communicate a lot with a "two word per message chatter"

* if you
* take my
* meaning

So it may be just that they are coming so close together and may not be a **real** issue.

**Comment by akashnimare** [comment]
Do you get the same behaviour on web (in browser)? You are getting the default behaviour of native notifications since I have not done anything with notifications yet.

**Comment by GervaisdeM** [comment]
I'm not sure... I will try to check this.

**Comment by akashnimare** [comment]
I have cross checked it on chrome. It's the default behaviour. Closing since it's not an issue of app.

**Comment by timabbott** [comment]
@GervaisdeM how are you reading the messages in this case?  Zulip's behavior is to only mark messages as read in the case that the user focuses the Zulip window, not just if you read them as they flow by in the desktop notifications (for example).  I'd like to understand if this is behaving as expected; if not, we should open an issue in the main Zulip server project.

**Comment by GervaisdeM** [comment]
Hmmm. I believe that I was reading the messages in the Electron client with it in the foreground. I haven't seen it since. I see that the issue is closed. Perhaps it should just be left closed and if I see the behaviour again. I'll make a better description in a new issue.

**Comment by GervaisdeM** [comment]
@akashnimare 
@timabbott 

Hey Guys... I managed to grab a screen snapshot of this. It's not a huge deal, but since it was happening, I snapped a picture.

You can see that Electron is in the foreground. I am at the bottom of the message window. Messages are coming in quickly. The message count is off. I have replied to her and there is one more message below my reply... It says, "14 message from Gail"

![screen shot 2016-08-09 at 3 59 36 pm](https://cloud.githubusercontent.com/assets/963514/17530514/3ed43e9c-5e4e-11e6-8245-c50f9ee1e57f.png)
