### ISSUE TITLE
clicking on a pasted screenshot is hard to recover from

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-electron#47]
If you click on a screenshot, it loads in-app rather than in a browser, and then you get stuck with no way to go back.

**Comment by akashnimare** [comment]
Did you try using `Alt + left_Arrow` which is the standard shortcut to go back. It works on OS X. I have not tested it on linux yet. Also as we have discussed here https://github.com/zulip/zulip-electron/issues/34 - all the links which belongs to the current zulip server (for example zulip.tabbott.net) will be opened in app only and rest will be opened in browser.

**Comment by timabbott** [comment]
Yes, I tried that, and it didn't work on Linux.

**Comment by timabbott** [comment]
Maybe the right fix for this is that we should set the links in the webapp for clicking on an uploaded image to open it in a new tab -- seems like that might be the actual core problem here (though there's also alt-leftarrow not working on Linux problem).

**Comment by akashnimare** [comment]
Personally I think opening images in new tab breaks the flow. UX wise we should open image/media in the same tab with some kind of lightbox/popup just like Quora/telegram/slack does.  
<img src="http://im2.ezgif.com/tmp/ezgif-1781578894.gif"/>

**Comment by akashnimare** [comment]
@timabbott just tested it on linux. For some reason Alt+leftarrow doesn't work on linux (in electron). So probably I have to remap it with something else.

**Comment by akashnimare** [comment]
@timabbott Added new shortcuts 
```
Back - CommandOrControl+[ 
Forward - CommandOrControl+]
```

**Comment by timabbott** [comment]
OK, do we also need to implement a lightbox sort of feature in the webapp to fully solve this problem?  I think we should address this as completely as possible since it was the main complaint we got about the electron app when we had a bunch of people trying it last week.

(Also, are those shortcuts documented somewhere?)

**Comment by akashnimare** [comment]
This is completely a different issue. We don't need to implement lightbox to resolve this.
I have documented few shortcuts in Readme -  https://github.com/zulip/zulip-electron#features

**Comment by timabbott** [comment]
Cool, that'll do for now but maybe we want to add a little "keyboard shortcuts" menu item eventually :)

**Comment by akashnimare** [comment]
Yes, we'll add it once we have more items to show.
