### ISSUE TITLE
Include zooming options in View menu

### ISSUE THREAD

**Issue by brainwane** [zulip/zulip-electron#48]
As a followup to #38: the View menu should include:

Zoom In Ctrl++
Zoom Out Ctrl+-
Original magnification Ctrl+0

**Comment by akashnimare** [comment]
Will it be useful? We have already implemented keyboard shortcuts for zooming feature. We can document it somewhere.

**Comment by brainwane** [comment]
@akashnimare Yes, it's useful. Accessibility best practices in browsers and in desktop applications in general say that if something's possible to do via a keyboard shortcut, it should also be discoverable via the dropdown menus. And I myself am much more likely to first look at the options available to me via the dropdown menus, and to expect that zooming options would be listed there under View.

**Comment by brainwane** [comment]
If there's a specific reason to avoid adding this to the View menu, I'm open to hearing it. But desktop applications that support zooming (browsers, LibreOffice, Thunderbird, etc.) usually include a Zoom item in their View menu or someplace similar (for instance, it's [an expected option in the Window menu for Apple applications](https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/MenuBarMenus.html#//apple_ref/doc/uid/20000957-CH29-SW1)), even when they also support a keyboard shortcut for it. In general, if a user has to go read documentation in order to use a feature, that's much less optimal than if we could have provided them with an easy discovery through the user interface.

**Comment by akashnimare** [comment]
Cool then let's add it 👍 .

**Comment by akashnimare** [comment]
@brainwane Added zooming options in Menu.
