### ISSUE TITLE
Add integrations with native notifications (e.g. dock bouncing)

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-electron#5]
This is probably the main feature of the existing desktop app.

**Comment by akashnimare** [comment]
@timabbott It's working. Could you please cross check it?

**Comment by timabbott** [comment]
Cool, I think this is really several cases to check:
* [ ] Linux
* [ ] OSX
* [ ] Windows
I'll test Linux shortly.

**Comment by timabbott** [comment]
Works on Linux!  One downside of the native Linux notifications is they don't seem to be clickable if you want to jump to that message like the default Chrome ones are; idunno if there's anything we can do about that but seems worth investigating...

**Comment by akashnimare** [comment]
Works on OSX too. Not sure about Windows. I'll have a look if we can make them clickable or not.

**Comment by akashnimare** [comment]
As of now desktop notifications are working on the following platforms - 
1. Windows 10
2. OSX (tested on OS X EL Capitan Version 10.11.6)
3. Linux (tested on Ubuntu 14.04/16.04)

**Comment by akashnimare** [comment]
Merging into #16
