### ISSUE TITLE
App should be titled Zulip, have Zulip logo

### ISSUE THREAD

**Issue by freyley** [zulip/zulip-electron#52]
---

#### Summary

Currently the app runs with the name Electron and the Electron logo.

#### Steps to reproduce

Open the app on Mac OS X using the `npm start` command.

**Comment by akashnimare** [comment]
This is the problem with Electron itself. App name and logo works fine in win and linux but in osx you will have to build .dmg or .app to show it. It will be automatically fixed on build.
