### ISSUE TITLE
Add option to not display unread messages

### ISSUE THREAD

**Issue by joelburget** [zulip/zulip-electron#54]
---

#### Summary

I find the unread notifier (red circle with a number inside) a little noisy based on its current configuration -- I'd prefer to turn it off of change the number to only count my private messages and @-mentions.

#### Steps to reproduce

Running OS X, I receive messages in a channel I don't really care about and get an unread notifier.

**Comment by timabbott** [comment]
@joelburget would you like that behavior in the webapp as well?  If so, we could probably just make this as a setting in the webapp (and the electron app would inherit that functionality).

**Comment by joelburget** [comment]
I don't think I'm shown the number of unread messages in the webapp, but I
imagine if I did see a count there I'd like it to go away.

**Comment by timabbott** [comment]
Yeah, the webapp shows the total unread count in the favicon.

**Comment by akashnimare** [comment]
@joelburget yes it's bit noisy. @timabbott Could we implement this in web app settings (receive notifications only for mentions/private messages etc)?

**Comment by timabbott** [comment]
Yeah, you can open an issue in the webapp for having the favicon count only include @-mentions/PMs (if I'm not mistaken, this is a different setting from whether to receive desktop notifications, which we already have settings for).

**Comment by akashnimare** [comment]
@timabbott yes, this is different from desktop notifications settings. Just FYI I am fetching the badge [counts](https://github.com/zulip/zulip-electron/blob/master/app/main/index.js#L57-L66) from the title of page.

**Comment by akashnimare** [comment]
Merging it here https://github.com/zulip/zulip/issues/1736.
