### ISSUE TITLE
Getting audible notifications on every message, with audible notifications turned off

### ISSUE THREAD

**Issue by freyley** [zulip/zulip-electron#55]
#### Summary

I'm getting beeps on every single message I receive, even though I have audible notifications turned off on both the global level and on each individual channel.

#### Steps to reproduce

Please include: 

I'm running master on Mac OS X 10.10

**Comment by timabbott** [comment]
That definitely seems like a bug.

**Comment by akashnimare** [comment]
I just tested it on ubuntu 14.04 and it works as expected. I think in OS X `system preferences `setting is overriding our app settings. @freyley for a temporary fix you can disable it via system preferences.

![image](https://cloud.githubusercontent.com/assets/2263909/17874086/17d0e0c2-68e7-11e6-97b5-0b6112ec26ad.png)

**Comment by freyley** [comment]
@akashnimare any idea why you have an Electron section of Notifications and I don't? I'm just running `npm start` and I wonder if maybe I need to package and install the zulip app to get that? I've been googling, but haven't found anything.

**Comment by akashnimare** [comment]
@freyley Don't no why it's not showing up in your system. It should automatically comes with electron itself.

**Comment by akashnimare** [comment]
@freyley can you test it latest build?

**Comment by freyley** [comment]
It hasn't beeped at me yet!

:)

**Comment by akashnimare** [comment]
Haha it won't 😄 .
