### ISSUE TITLE
Jumping words in compose box on Mac

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-electron#56]
I got a bug report from a user about "not being able to move alone the line one word at a time with cmd+left/right on Mac".  I tested and this works correctly on Linux, so it's probably a Mac-specific issue.

**Comment by akashnimare** [comment]
I think it's happening because of this 
https://github.com/zulip/zulip-electron/blob/master/app/main/index.js#L176

**Comment by akashnimare** [comment]
Fixed.
