### ISSUE TITLE
Electron crashing

### ISSUE THREAD

**Issue by GervaisdeM** [zulip/zulip-electron#59]
---

#### Summary

Crash

#### Steps to reproduce

- Electron opens off screen (location from my larger monitor, maybe). When I drag it to center of my laptop, Electron crashes

- macOS Sierra
- brew installed
  - node --version v6.3.1
  - npm --version 3.10.3

<img width="928" alt="screen shot 2016-08-23 at 5 48 49 pm" src="https://cloud.githubusercontent.com/assets/963514/17909347/81cb5318-695a-11e6-81fc-74df334991a7.png">

Terminal shows:

```bash
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! Zulip-desktop@0.0.1 start: `electron .`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the Zulip-desktop@0.0.1 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Zulip-desktop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Zulip-desktop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Zulip-desktop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gervais/Development/GdeM/zulip-electron/npm-debug.log
```

Log attached:
[npm-debug.log.zip](https://github.com/zulip/zulip-electron/files/433552/npm-debug.log.zip)

**Comment by akashnimare** [comment]
@GervaisdeM I was just looking into this issue. Window is not able to restore it's position when moved/resize etc.

**Comment by GervaisdeM** [comment]
@akashnimare Let me know if there is anything I can do to test.  :-)

**Comment by akashnimare** [comment]
@GervaisdeM fixed. Can can test it?

**Comment by GervaisdeM** [comment]
@akashnimare Already on it. 😄 

👍 No more errors.

**Comment by akashnimare** [comment]
Cool 🎆 .
