### ISSUE TITLE
How Can I Delete a Realm From My Electron App?

### ISSUE THREAD

**Issue by straussmaus** [zulip/zulip-electron#590]
---

Running Linux.  Version of Electron Zulip App is 2.3.82.  AppImage.

I added a realm (which exists) but I don't have access to this realm and I don't need it.  But the icon on the left side won't leave.  I like a clean desktop.  How do I make him go away?

**Comment by akashnimare** [comment]
You can delete a realm using `Settings > Organizations > Disconnect`

![image](https://user-images.githubusercontent.com/2263909/47614195-e3314380-dac1-11e8-846e-e5fa18625c76.png)

**Comment by akashnimare** [comment]
@rishig we should document this somewhere in `/help`.
