### ISSUE TITLE
Add a test suite for the app and setup in Travis CI

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-electron#6]
It looks like this might be a reasonable framework: http://electron.atom.io/spectron/

**Comment by kritkaran94** [comment]
@timabbott Can I take up this issue?

**Comment by kritkaran94** [comment]
@akashnimare Does it work for a mac ?

**Comment by akashnimare** [comment]
> Can I take up this issue?

Yes, you can work on this. 

> Does the installation work for a mac too. Bcz all i get is a white screen with Zulip on top ?

It should work. Although I haven't tested it with latest code.

**Comment by kritkaran94** [comment]
@akashnimare All I get is a blank white screen as shown above.

**Comment by akashnimare** [comment]
Okay. Let me check then.

**Comment by kritkaran94** [comment]
Thanks for that

**Comment by akashnimare** [comment]
@kritkaran94 Fixed it. Can you check it again?

**Comment by kritkaran94** [comment]
@akashnimare I will do that and get back to you.

**Comment by kritkaran94** [comment]
Firstly, I get this screen
![screen shot 2016-07-03 at 8 37 21 pm](https://cloud.githubusercontent.com/assets/10063868/16546113/0193b33a-415e-11e6-979c-6d944638a772.png)
later if I enter zulip.example.com I get a blank white screen.

**Comment by akashnimare** [comment]
@kritkaran94  **zulip.example.com** is just a placeholder. Try using zulip.com

**Comment by kritkaran94** [comment]
It works!! Thanks for that. Now, I will work on the tests.

**Comment by akashnimare** [comment]
For this you will have to either remove domain.json and npm start or you could use change domain options from tray menu.

**Comment by kritkaran94** [comment]
Ah.. I have one problem while registering 
![screen shot 2016-07-03 at 8 47 08 pm](https://cloud.githubusercontent.com/assets/10063868/16546158/69cead32-415f-11e6-9f47-126e243c8a48.png)

**Comment by akashnimare** [comment]
@kritkaran94 You can use **zulip.tabbott.net** for testing.

**Comment by kritkaran94** [comment]
@akashnimare I will try that.

**Comment by kritkaran94** [comment]
@akashnimare I am working on adding a test suite. Facing some issues though, I would update you on the same in a few days.

**Comment by akashnimare** [comment]
@kritkaran94 Cool.

**Comment by akashnimare** [comment]
@kritkaran94 any updates :smile: ?

**Comment by kritkaran94** [comment]
Not yet @akashnimare. Will try to make progress soon.

**Comment by akashnimare** [comment]
@kritkaran94 Cool.

**Comment by akashnimare** [comment]
@timabbott I have added some test suites. 
**xo** checks for linting errors and **mocha+spectron** checks whether app is opened properly or not.

**Comment by timabbott** [comment]
Nice!  I activated Travis CI for this repo; you may need to push code for it to actually run a build though.

**Comment by akashnimare** [comment]
Added CI for windows on appveyor. Check it out here -
https://ci.appveyor.com/project/akashnimare/zulip-electron/branch/master
