### ISSUE TITLE
Typo in "Not a Valid Zulip Server"

### ISSUE THREAD

**Issue by GervaisdeM** [zulip/zulip-electron#65]
<img width="397" alt="screen shot 2016-08-31 at 11 21 28 pm" src="https://cloud.githubusercontent.com/assets/963514/18153224/64826a84-6fd2-11e6-8e65-0bcc32a5fe85.png">
---
Please include: 
- macOS X Sierra
- put in invalid server

**Comment by akashnimare** [comment]
@GervaisdeM Thanks. Fixed.
