### ISSUE TITLE
Can't edit sent message

### ISSUE THREAD

**Issue by GervaisdeM** [zulip/zulip-electron#66]
---

- macOS Sierra
- Steps to reproduce:
  - Send message:
  - Try to edit it
  - The message/edit window is greyed out and cursor changes to 🚫 (but also grey)
  - Can't edit, but can click `Save` or `Cancel`

This happens with Electron (latest master) and Zulip 0.0.1-Alpha client.

![screen shot 2016-09-01 at 11 15 13 am](https://cloud.githubusercontent.com/assets/963514/18170812/10ba0f24-7036-11e6-9846-08bfdbf09bb8.png)

**Comment by GervaisdeM** [comment]
Apparently, this is due to a new feature in Zulip 1.4.0. 
It's not a bug at all.

Sorry, this issue should be closed,

**Comment by timabbott** [comment]
Closing, thanks @GervaisdeM!  I opened https://github.com/zulip/zulip/issues/1761 for the root issue here (that the app doesn't make it clear that you can't edit the message).
