### ISSUE TITLE
Twitter-bot images not loading, but only in client.

### ISSUE THREAD

**Issue by GervaisdeM** [zulip/zulip-electron#67]
I upgraded Zulip to 1.4.0 and now twitter-bot delivered messages are not displaying images, but only in the client.

- macOS Sierra
- Zulip-server 1.4.0

Electron Client:
<img width="672" alt="screen shot 2016-09-01 at 8 29 45 pm" src="https://cloud.githubusercontent.com/assets/963514/18187799/1da0003e-7083-11e6-943c-6e36a6be94fc.png">
 
Web Browser:
<img width="902" alt="screen shot 2016-09-01 at 8 29 27 pm" src="https://cloud.githubusercontent.com/assets/963514/18187817/3629c626-7083-11e6-9026-e2e8f4fd6664.png">

**Comment by timabbott** [comment]
@akashnimare we can setup the Zulip twitter integration on zulip.tabbott.net to make it easy to reproduce this if you like...

**Comment by akashnimare** [comment]
@timabbott yes, please.

**Comment by timabbott** [comment]
OK, setup done! :)

**Comment by akashnimare** [comment]
@GervaisdeM could you reproduce this on [zulip.tabbott.net](zulip.tabbott.net) ?

**Comment by akashnimare** [comment]
Fixed in [34a62e2](https://github.com/zulip/zulip-electron/commit/34a62e2d10ce0c369e5f043e20e6fc4d71dbdfc7).

**Comment by timabbott** [comment]
@akashnimare I think we shouldn't be disabling the web security option -- that's important to protecting users of the app from potential attacks.  Why did you feel you needed to disable it?  Based on http://electron.atom.io/docs/api/browser-window/, it seems to me that maybe what you wanted to do was just enable allowDisplayingInsecureContent?

**Comment by akashnimare** [comment]
> protecting users of the app from potential attacks

@timabbott I didn't thought about this. Enabling `allowDisplayingInsecureContent` option will also work.

**Comment by timabbott** [comment]
Great!
