### ISSUE TITLE
Open image in default browser

### ISSUE THREAD

**Issue by freyley** [zulip/zulip-electron#68]
---
Please include: 
- `Operating System`
Running Zulip-Electron (latest master) on Mac OS X

- `Clear steps to reproduce the issue`

Have someone upload an image into Zulip. Click on the image until it opens in Zulip-Electron.

- `Relevant error messages and/or screenshots`

No error messages. The image takes over the window. There's no back, or other navigation, even in the right-click menu, so you're stuck.

**Comment by akashnimare** [comment]
You can go back using `Command + [` as mentioned here -
https://github.com/zulip/zulip-electron#features

**Comment by timabbott** [comment]
@akashnimare I think we should try to solve the issue that clicking on an uploaded image does a wrong thing in the first place.  Even if we later want to move to a lightbox style approach, I think for now we should make the app open images in-browser.

What do you think?

**Comment by timabbott** [comment]
(Empirically this seems to be the most common issue people encounter using the app)

**Comment by akashnimare** [comment]
@timabbott here is the logic I'm using https://github.com/zulip/zulip-electron/blob/master/app/main/index.js#L198. Now to open image in browser I'll have to manually check if clicked link/url contains .png/.jpg etc.

**Comment by timabbott** [comment]
Hmm, I'm not sure that's true -- I think the rest of the URL is different for image files.

**Comment by akashnimare** [comment]
@timabbott can you test it now? Let me know if this is what you want.

**Comment by freyley** [comment]
Worked correctly for me on master today.
