### ISSUE TITLE
Add auto-update support [Windows]

### ISSUE THREAD

**Issue by akashnimare** [zulip/zulip-electron#74]
Available options - 
https://www.npmjs.com/package/electron-updater
https://github.com/ArekSredzki/electron-release-server

More info -
https://github.com/electron/electron/blob/master/docs/api/auto-updater.md

**Comment by slurdge** [comment]
Seems like electron-update is in maintenance only mode.

> This project is in maintainance only mode. It is recommended that you use the electron-packager and electron-builder projects to generate complete installable versions of your applications and use either the OS specific stores or some other mechanism for distributing your installers.

However electron-builder does have auto-update support. So it may be a better option for packaging&updating.

**Comment by akashnimare** [comment]
@slurdge yes, electron-builder seems to be a better option.

**Comment by akashnimare** [comment]
This feature has been added in macOs.

**Comment by akashnimare** [comment]
Windows automatic updates added in new beta release - [Beta-v0.5.3](https://github.com/zulip/zulip-electron/releases/tag/v0.5.3)
