### ISSUE TITLE
can't connect to localhost:9991 via electron app

### ISSUE THREAD

**Issue by brainwane** [zulip/zulip-electron#78]
I have a development version of the Zulip web app running at http://localhost:9991/ . I can access it in my regular desktop browser (Firefox). When I try to access it via the Electron app, the "checking..." spinner spins but never connects nor errors out. I've also tried http://zulip.zulipdev.com:9991/ and I've tried localhost:9991 . Same (lack of) result.

I'm running Linux Mint 17 'Qiana' (based on Ubuntu 14.04) and I'm running the latest zulip-electron code.

**Comment by akashnimare** [comment]
@brainwane yeah it's a known issue. I'm working on that.

**Comment by Lplenka** [comment]
@zulipbot claim , I have solved this issue , the switching b/w localhost & online servers also working fine...i am ready for a PR

**Comment by Lplenka** [comment]
@akashnimare @timabbott  any comments ? IHope this fix helps

**Comment by akashnimare** [comment]
WAIT on please! I'll see, once I get the chance.

**Comment by Lplenka** [comment]
Yes sure ! I was just curious about feedback , so that i could work further if needed.

**Comment by akashnimare** [comment]
Fixed. Thanks @Lplenka 😄

**Comment by Lplenka** [comment]
Thanks! @akashnimare  happy to contribute 😄 Will work on other issues
