### ISSUE TITLE
No titlebar in OSX

### ISSUE THREAD

**Issue by anotherboojum** [zulip/zulip-electron#8]
I'm on OSX 10.11.3.   There is no titlebar on top of the window, so I can't move the window around, except by resizing it.    The colored dots are on top of the inside of the window content, on top of the "zulip" image in the top left. 

<img width="235" alt="screen shot 2016-06-17 at 7 15 29 pm" src="https://cloud.githubusercontent.com/assets/20006524/16167309/64e7d528-34c1-11e6-859e-33db158c8968.png">

**Comment by akashnimare** [comment]
@anotherboojum Can you check it again? I have fixed it.

**Comment by anotherboojum** [comment]
Yup, there's a title bar and I can move it around.  Yay!

(I can't log in, though, so I kind of preferred the previous version, but that's probably a separate issue)

**Comment by akashnimare** [comment]
Please check it again. It's fixed. This app is in very early stage. It'll get better.
