### ISSUE TITLE
libnotify errors Centos 6.7

### ISSUE THREAD

**Issue by ezeri** [zulip/zulip-electron#85]
Copying info from  zulip/zulip-desktop#52

I get errors with the notification system though.

```
(electron:2745241): libnotify-CRITICAL **: notify_notification_new: assertion `attach == NULL || GTK_IS_WIDGET (attach)' failed

(electron:2745241): libnotify-CRITICAL **: notify_notification_add_action: assertion `notification != NULL' failed

(electron:2745241): libnotify-CRITICAL **: notify_notification_set_image_from_pixbuf: assertion `notification != NULL' failed

(electron:2745241): libnotify-CRITICAL **: notify_notification_set_timeout: assertion `notification != NULL' failed

(electron:2745241): libnotify-CRITICAL **: notify_notification_show: assertion `notification != NULL' failed

(electron:2745241): libnotify-CRITICAL **: notify_notification_close: assertion `notification != NULL' failed
```

We are currently using Centos 6.7 with libnotify.x86_64 0.5.0-1.el6

Any ideas would be welcome.

Cheers,

Belisaire.

**Comment by timabbott** [comment]
Hmm, it may be worth Googling for those errors + "electron" to see if that's a known electron bug with a recommended solution...

**Comment by akashnimare** [comment]
@ezeri I don't see such errors on Ubuntu 14.04. Maybe it's distro-specific 🤔 . I'll see what I can do to resolve this.

**Comment by ezeri** [comment]
@akashnimare Can you check what version of libnotify you are using ?

We are on 0.5.0, and the latest is 0.7.7, but the 0.7+ versions require gnome3 and we use gnome2. I am afraid this is a backward compatibility issue. I tried updating our version, but am having great difficulties finding a version of libnotify that is buildable on gnome2 of any version after the 0.5.0.

Would you be able to test on a gnome2 distro to see if it is the case ?

Cheers,

Belisaire.

@timabbott  I have been looking around since thursday. All I have found are references for a similar issue in gnome3, but nothing similiart to our case. (At least nothing with an actual solution apart from "Update your distrib", which I can not.)

**Comment by akashnimare** [comment]
@ezeri could you test this error on latest build https://github.com/zulip/zulip-electron/commit/bd6616e065738a97b1226420542e046ae04d9bc3?
> Can you check what version of libnotify you are using ?

I'm on Ubuntu 16.04 (Unity) and using libnotify - 0.7.6.

> Would you be able to test on a gnome2 distro to see if it is the case ?

I can't :(. Maybe someone in our community can test it.

Btw Is it possible for you guys to use Ubuntu MATE? It's an updated and maintained version of GNOME 2, with an official 16.04 release as well.

**Comment by akashnimare** [comment]
@ezeri any update on this?

**Comment by akashnimare** [comment]
Closing until more info given.
