### ISSUE TITLE
OSX: clicking links open Electron mini-window

### ISSUE THREAD

**Issue by anotherboojum** [zulip/zulip-electron#9]
Clicking on a link in a zulip message opens an smaller window in Electron as a browser, rather than opening in my default browser.

**Comment by jjst** [comment]
Can confirm this happens on Ubuntu as well.

**Comment by akashnimare** [comment]
@jjst @anotherboojum Thanks for reporting this. I have fixed it. Please check it again.

**Comment by jjst** [comment]
Yup, works for me!
