### ISSUE TITLE
Unable to Get to the Login Screen on OS X

### ISSUE THREAD

**Issue by zbreit18** [zulip/zulip-electron#91]
***OS:*** OS X El Capitan (V. 10.11.6)

Here are all the steps I took to get this bug. It could be an error on my part, but I just wanted to post it here in case it isn't.

1) The first step I took to run the electron app was forking and cloning the `zulip-electron` repo on github.
2) Next, I cd’d into the directory and ran `npm install` followed by `npm start`. There didn’t seem to be any errors until…
3) The app opened up on my desktop. For a second, the login screen with the github/google login button flashed onto my screen, but the window quickly turned white. I tried looking through the menus, and even changing the channel to chat.zulip.org, but it didn’t work either. Looking back at my terminal, it gave me this error.
```
#
# Fatal error in ../../v8/src/api.cc, line 1082
# Check failed: !value_obj->IsJSReceiver() || value_obj->IsTemplateInfo().
#
==== C stack trace ===============================
1: V8_Fatal
2: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
3: (anonymous namespace)::Init(v8::Local<v8::Object>, v8::Local<v8::Object>)
4: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
6: v8::internal::Builtins::InvokeApiFunction(v8::internal::Isolate, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>)
7: v8::internal::PrototypeIterator::AdvanceFollowingProxiesIgnoringAccessChecks()
8: 0x3a5dd5a06147
```
Here are some screenshots/gifs of what happens when using the app:

***The blank screen I get after running `npm start`***
<img width="999" alt="screen shot 2016-11-29 at 10 25 06 pm" src="https://cloud.githubusercontent.com/assets/6632788/20775363/8846bfa4-b728-11e6-8c93-a59b3de1a59d.png">

***Opening up Chrome Inspector yields few results***
<img width="998" alt="screen shot 2016-11-30 at 5 48 06 pm" src="https://cloud.githubusercontent.com/assets/6632788/20775364/8a37de4c-b728-11e6-89ed-e44621112518.png">

***When I reloaded the page while open to the `Devtron` section of the Chrome Inspector***
<img width="905" alt="screen shot 2016-11-30 at 6 03 04 pm" src="https://cloud.githubusercontent.com/assets/6632788/20775367/8c60d0fc-b728-11e6-90b2-445d8cb0acac.png">

***When I reloaded the page on the `Network` section. Showed that the web requests for Source Sans Pro were still pending***
<img width="1278" alt="screen shot 2016-11-30 at 6 18 20 pm" src="https://cloud.githubusercontent.com/assets/6632788/20775549/7c7f4d66-b729-11e6-9a44-b7746d22ea28.png">

**Comment by akashnimare** [comment]
@zbreit18 hey, sorry for the late response as I was busy in exams. 
BTW I have never encountered such errors. Could you please follow these steps - 
* update node to v6.3.1 + npm to 3.10.3
* rm -rf node_modules && rm -rf app/node_modules
* npm install
* npm start
Let me know if it works.

**Comment by zbreit18** [comment]
Wow, I'm surprised fixing it was as simple as that. Looks like I was using the wrong version of node. Thanks for the help 👍.

**Comment by akashnimare** [comment]
@zbreit18 happy to help 😀

**Comment by timabbott** [comment]
@akashnimare do you think we should include in the installation instructions documentation on getting the right version of node?

Also, do the bundled versions of the app come with a node install to handle this?

**Comment by akashnimare** [comment]
@timabbott updated installation instructions.

> Also, do the bundled versions of the app come with a node install to handle this?

yes 😄
