### ISSUE TITLE
all links open in a zulip window

### ISSUE THREAD

**Issue by matthewalbani** [zulip/zulip-electron#99]
opening any link creates a new zulip window. If this is intended an option to disable would be nice. From earlier release notes it seems like external links are meant to open in the default browser.
-
Zulip 0.5.4
Electron 1.4.7
darwin x64 15.6.0

<img width="1440" alt="screen shot 2017-01-12 at 1 56 41 pm" src="https://cloud.githubusercontent.com/assets/7443459/21909967/03fc06dc-d8cf-11e6-8445-7850be34b6c5.png">

**Comment by matthewalbani** [comment]
seems related to https://github.com/zulip/zulip-electron/issues/9 but its closed

**Comment by timabbott** [comment]
@akashnimare when we fix this, it may make sense to add a test suite for exactly when things should open new windows.

**Comment by akashnimare** [comment]
@timabbott yeah, we definitely need to write some test suite for this 😭

**Comment by akashnimare** [comment]
@matthewalbani are you using the latest [release](https://github.com/zulip/zulip-electron/releases/tag/v0.5.4)? I can't reproduce this on https://github.com/zulip/zulip-electron/commit/5f027820f405ae8fecffe2b5962e3ecfa4701c80.

**Comment by matthewalbani** [comment]
hrm its not doing it for me any more either....

**Comment by akashnimare** [comment]
@matthewalbani I'm curious - why did you get this error, were you using the older version of zulip-electron?

**Comment by matthewalbani** [comment]
I'm not really sure. I think it went away after a restart though.

**Comment by matthewalbani** [comment]
I think it went away after a restart. I had not restarted since s itching to that version, but I have no evidence that's what actually fixes it.
